config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Authentication
  devise_for :users, {}

  # Application
  scope "(:locale)", locale: /en|pl/ do
    root to: 'home#index'
    namespace :blog do
      resources :posts, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_categories_on_name     (name) UNIQUE
#  index_categories_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged]

  # Relationships
  has_many :posts, dependent: :destroy
  belongs_to :user

  # Validations
  validates :name, presence: true, uniqueness: true
end

app/models/newsletter.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: newsletters
#
#  id         :bigint           not null, primary key
#  cancel_at  :datetime
#  email      :string
#  name       :string
#  status     :integer
#  token      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_newsletters_on_email  (email) UNIQUE
#  index_newsletters_on_token  (token) UNIQUE
#
class Newsletter < ApplicationRecord
  # Enum
  enum status: { enabled: 0, disabled: 1 }

  # Callbacks
  after_create :signup

  # Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :token, uniqueness: { case_sensitive: true }

  # Methods
  def self.by_token(token)
    find_by(token: token)
  end

  def signup
    NewsletterSignup.call(newsletter: self)
  end

  def cancel
    NewsletterCancel.call(newsletter: self)
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  body        :text
#  featured    :boolean          default(FALSE)
#  published   :boolean          default(FALSE)
#  slug        :string
#  tags        :string
#  thumbnail   :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_posts_on_category_id  (category_id)
#  index_posts_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged]

  # Scope
  scope :by_title, ->(title) { where('title LIKE ?', "%#{title}%") }
  scope :by_tag, ->(tag) { where('tags LIKE ?', "%#{tag}%") }

  scope :featured, -> { where(featured: true) }
  scope :published, -> { where(published: true) }
  scope :draft, -> { where(published: false) }

  # Uploader
  has_one_attached :thumbnail

  # Validations
  validates :title, presence: true
  validates :body, presence: true

  # Relationships
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Relationships
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/blog/posts_controller.rb
# frozen_string_literal: true

module Blog
  class PostsController < ApplicationController
    before_action :set_post, only: [:show]

    def index
      @posts = Post.order(created_at: :desc)
                   .page(params[:page])
                   .per(9)
    end

    def show; end

    private

    def set_post
      @post = Post.friendly.find(params[:id])
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/blog/posts/_post.html.erb
<div class="col-md-4">
  <div class="panel panel-default post">
    <div class="panel-body">
      <h5 class='category'>Docker</h5>
      <h4 class='title bold'>
        <%= link_to truncate(post.title, length: 40), blog_post_path(post) %>
      </h4>
      <ul class="info list-unstyled list-inline">
        <li><%= time_ago_in_words(post.created_at) %></li>
        <li><%= post.reading_time %></li>
      </ul>
    </div>
  </div>
</div>

app/views/blog/posts/index.html.erb
<%= provide :title, 'Blog' %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>

<section id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="bold">Ruby Polska Blog</h1>
        <p>
          <%= t('blog.hero.subtitle.line_one') %><br>
          <%= t('blog.hero.subtitle.line_two') %><br/>
          <%= t('blog.hero.subtitle.line_three') %></p>
        <br />

        <%= link_to '#',
        class: 'btn btn-default btn-lg' do %>
          <%= t('blog.hero.newsletter.signup') %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-8">
            <div class="panel panel-default post">
              <div class="panel-body">
                <h5 class='category'>Docker</h5>
                <h3 class='title bold'>Comandos Docker mais utilizados</h3>

                <ul class="info list-unstyled list-inline">
                  <li>há 4 dias</li>
                  <li>3 min de leitura</li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="panel panel-default post">
              <div class="panel-body">
                <h5 class='category'>Docker</h5>
                <h3 class='title bold'>Comandos Docker mais utilizados</h3>

                <ul class="info list-unstyled list-inline">
                  <li>há 4 dias</li>
                  <li>3 min de leitura</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <%= render @posts %>

          <div class="col-md-12">
            <div class='text-center'>
              <%= paginate(@posts) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/blog/posts/show.html.erb
<%= provide :title, @post.title %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div id="heading">
              <h1 class='text-center'><%= @post.title %></h1>
              <br />

              <ul class="text-center list-unstyledt list-inline">
                <li>
                  <i class="fa-solid fa-tag"></i>
                  Carreira
                </li>
                <li>
                  <i class="fa-regular fa-calendar"></i>
                  about <%= time_ago_in_words(@post.created_at) %>
                </li>
                <li>
                  <i class="fa-regular fa-clock"></i>
                  <%= @post.reading_time %>
                </li>
              </ul>
            </div>

            <div id="body"><br />
              <%= raw(@post.body) %>
            </div>

            <div id="recomendations"><br />
              <h3 class='bold text-center'>Recomendations for you</h3>

              <div class='row'><br />
                <% Post.all.limit(3).each do |post| %>
                  <%= render partial: 'blog/posts/post/', locals: { post: post } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= provide :title, 'Home' %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>

<section id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class='title'>Ruby <br /><span class='polska'>Polska</span></h1>
        <p class='subtitle'><%= t('hero.subtitle.one') %>
        <span class='bold'><%= t('hero.subtitle.two')%></span><br />
        <%= t('hero.subtitle.three') %>
        <span class='bold'><%= t('hero.subtitle.four') %></span>
        <%= t('hero.subtitle.five') %>.</p>
        <ul class='list-unstyled list-inline actions'>
          <li>
            <%= link_to 'https://discord.gg/myk3SHsz5g',
            target: :_blank,
            class: 'btn btn-primary btn-lg' do %>
              <i class="fa-brands fa-discord"></i>
              Discord
            <% end %>
          </li>
          <li>
            <%= link_to 'https://instagram.com/rubypolska',
            target: :_blank,
              class: 'btn btn-primary btn-lg' do %>
              <i class="fa-brands fa-instagram"></i>
              Instagram
            <% end %>
          </li>
          <li>
            <%= link_to 'https://github.com/rubypolska',
             target: :_blank,
             class: 'btn btn-primary btn-lg' do %>
              <i class="fa-brands fa-github"></i>
              Github
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class='row'>
          <div class='col-md-8'>
            <p>Ruby Polska, 2024 - <%= Date.today.year %></p>
            <p><%= t('footer.made_with') %></p>
            <p>&copy <%= t('footer.copyright') %></p>
          </div>

          <div class="col-md-4">
            <ul class='list-unstyled list-inline text-right'>
              <li>
                <%= link_to 'https://linkedin.com/in/rubypolska' do %>
                  <i class="fa-brands fa-linkedin ico"></i>
                <% end %>
              </li>
              <li>
                <%= link_to 'https://youtube.com/@rubypolska' do %>
                  <i class="fa-brands fa-youtube ico"></i>
                <% end %>
              </li>
              <li>
                <%= link_to 'https://instagram.com/rubypolska' do %>
                  <i class="fa-brands fa-instagram ico"></i>
                <% end %>
              </li>
              <li>
                <%= link_to 'https://github.com/rubypolska' do %>
                  <i class="fa-brands fa-github ico"></i>
                <% end %>
              </li>
              <li>
                <%= link_to 'https://discord.gg/myk3SHsz5g' do %>
                  <i class="fa-brands fa-discord ico"></i>
                <% end %>
              </li>
            </ul>
            <p class='text-right'>
              <%= link_to 'https://youtube.com/', class: 'email' do %>
                <i class="fa-regular fa-envelope"></i>
                witaj@rubypolska.pl
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <nav class="navbar navbar-default">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path,
        class: 'navbar-brand' do %>
          Ruby Polska
      <% end %>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-center navbar-email">
        <li>
          <%= link_to 'mailto:witaj@rubypolska.pl' do %>
            <i class="fa-regular fa-envelope"></i>
            witaj@rubypolska.pl
          <% end %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= I18n.locale.upcase %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'EN', url_for(locale: 'en') %></li>
            <li><%= link_to 'PL', url_for(locale: 'pl') %></li>
          </ul>
        </li>
        <li><%= link_to t('header.nav.partner'), '#' %></li>
        <li><%= link_to t('header.nav.home'), root_path %></li>
        <li><%= link_to t('header.nav.blog'), blog_posts_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title><%= yield :title %> | Ruby Polska</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :stylesheet %></style>
    <script type="text/javascript"><%= yield :javascript %></script>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'>
    <%= render partial: 'layouts/header' %>
      <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>